language: python
python:
  - 3.7
  - 3.9

notifications:
  on_success: change
  on_failure: change

# Miniconda-based setup of the Scipy stack Based on
# https://gist.github.com/dan-blanchard/7045057.

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -f
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv

# Install packages
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.9 ]]; then conda install --yes python=$TRAVIS_PYTHON_VERSION argparse; fi
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy
  - python setup.py install

# See: https://github.com/coagulant/coveralls-python.  When I have tests, this should be "script".
# nosetests --with-coverage --cover-package=multipool --logging-level=INFO
before_script:
  - pip install coveralls
  - coverage run --source=multipool setup.py test

script: python mp_inference.py poolK1_chr12.txt -n 100 -np

sudo: false

after_success:
  - coveralls
